version: '3'

services:
  real_estate:
    build: .
    volumes:
     - .:/real_estate
    ports:
      - 3000:3000
    command: rails server -u webrick -p 8000
    environment:
      HOST_DB: db
      PORT_DB: 5432
    env_file:
      - db.env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    env_file:
      - db.env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
volumes:
   db: